# Generated by Django 2.2.7 on 2019-11-21 05:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=150)),
                ('suburb', models.CharField(max_length=50)),
                ('postcode', models.IntegerField(validators=[property.models.valid_postcode])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('no_guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('no_beds', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('no_bathrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('owner_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('property_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
    ]
