# Generated by Django 2.2.7 on 2019-11-14 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reviews.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_property',
            fields=[
                ('booking_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booking.Booking')),
                ('description', models.CharField(max_length=200)),
                ('rating', models.IntegerField(validators=[reviews.models.RatingValidator])),
            ],
        ),
        migrations.CreateModel(
            name='Review_user',
            fields=[
                ('booking_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booking.Booking')),
                ('description', models.CharField(max_length=200)),
                ('rating', models.IntegerField(validators=[reviews.models.RatingValidator])),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner reviewing their client')),
            ],
        ),
    ]
