# Generated by Django 2.2.7 on 2019-11-22 23:06

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_property',
            name='rating',
            field=models.FloatField(validators=[reviews.models.RatingValidator]),
        ),
    ]
