# Generated by Django 2.2.6 on 2019-10-20 21:22

from django.db import migrations, models
import django.db.models.deletion
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_property',
            name='id',
        ),
        migrations.RemoveField(
            model_name='review_user',
            name='id',
        ),
        migrations.AlterField(
            model_name='review_property',
            name='booking_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booking.Booking'),
        ),
        migrations.AlterField(
            model_name='review_property',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review_property',
            name='rating',
            field=models.IntegerField(validators=[reviews.models.RatingValidator]),
        ),
        migrations.AlterField(
            model_name='review_user',
            name='booking_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booking.Booking'),
        ),
        migrations.AlterField(
            model_name='review_user',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review_user',
            name='rating',
            field=models.IntegerField(validators=[reviews.models.RatingValidator]),
        ),
    ]
