# Generated by Django 2.2.6 on 2019-10-20 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20191020_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_property',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
