# Generated by Django 2.2.6 on 2019-10-20 22:26

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20191020_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_property',
            name='rating',
            field=models.IntegerField(validators=[reviews.models.RatingValidator]),
        ),
    ]
